/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // root type
    author?: string | null; // String
    bookCloudinaryId?: string | null; // String
    bookFile?: string | null; // String
    categoryId?: string | null; // String
    cloudinaryId?: string | null; // String
    description?: string | null; // String
    id?: number | null; // Int
    image?: string | null; // String
    title?: string | null; // String
  }
  Favorite: { // root type
    bookId?: number | null; // Int
    id?: number | null; // Int
    userId?: number | null; // Int
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email?: string | null; // String
    firstName?: string | null; // String
    id?: number | null; // Int
    lastName?: string | null; // String
    password?: string | null; // String
    role?: string | null; // String
  }
  category: { // root type
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // field return type
    author: string | null; // String
    bookCloudinaryId: string | null; // String
    bookFile: string | null; // String
    categoryId: string | null; // String
    cloudinaryId: string | null; // String
    description: string | null; // String
    id: number | null; // Int
    image: string | null; // String
    title: string | null; // String
  }
  Favorite: { // field return type
    bookId: number | null; // Int
    id: number | null; // Int
    userId: number | null; // Int
  }
  Mutation: { // field return type
    createBook: NexusGenRootTypes['Book'] | null; // Book
    createCategory: NexusGenRootTypes['category']; // category!
    createFavorite: NexusGenRootTypes['Favorite']; // Favorite!
    deleteBook: NexusGenRootTypes['Book'] | null; // Book
    deleteCategory: NexusGenRootTypes['category']; // category!
    deleteFavorite: NexusGenRootTypes['Favorite']; // Favorite!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    updateBook: NexusGenRootTypes['Book'] | null; // Book
    updateCategory: NexusGenRootTypes['category']; // category!
    updateUser: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    books: Array<NexusGenRootTypes['Book'] | null> | null; // [Book]
    categories: Array<NexusGenRootTypes['category'] | null> | null; // [category]
    favorites: Array<NexusGenRootTypes['Favorite'] | null>; // [Favorite]!
    oneBook: NexusGenRootTypes['Book'] | null; // Book
    oneCategory: NexusGenRootTypes['category'] | null; // category
    oneFavorite: NexusGenRootTypes['Favorite']; // Favorite!
    oneUser: NexusGenRootTypes['User']; // User!
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  User: { // field return type
    email: string | null; // String
    firstName: string | null; // String
    id: number | null; // Int
    lastName: string | null; // String
    password: string | null; // String
    role: string | null; // String
  }
  category: { // field return type
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Book: { // field return type name
    author: 'String'
    bookCloudinaryId: 'String'
    bookFile: 'String'
    categoryId: 'String'
    cloudinaryId: 'String'
    description: 'String'
    id: 'Int'
    image: 'String'
    title: 'String'
  }
  Favorite: { // field return type name
    bookId: 'Int'
    id: 'Int'
    userId: 'Int'
  }
  Mutation: { // field return type name
    createBook: 'Book'
    createCategory: 'category'
    createFavorite: 'Favorite'
    deleteBook: 'Book'
    deleteCategory: 'category'
    deleteFavorite: 'Favorite'
    login: 'AuthPayload'
    signup: 'AuthPayload'
    updateBook: 'Book'
    updateCategory: 'category'
    updateUser: 'User'
  }
  Query: { // field return type name
    books: 'Book'
    categories: 'category'
    favorites: 'Favorite'
    oneBook: 'Book'
    oneCategory: 'category'
    oneFavorite: 'Favorite'
    oneUser: 'User'
    users: 'User'
  }
  User: { // field return type name
    email: 'String'
    firstName: 'String'
    id: 'Int'
    lastName: 'String'
    password: 'String'
    role: 'String'
  }
  category: { // field return type name
    id: 'Int'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createBook: { // args
      author: string; // String!
      bookFile: string; // String!
      categoryId: number; // Int!
      description: string; // String!
      image: string; // String!
      title: string; // String!
    }
    createCategory: { // args
      name: string; // String!
    }
    createFavorite: { // args
      bookId: number; // Int!
    }
    deleteBook: { // args
      id: number; // Int!
    }
    deleteCategory: { // args
      id: number; // Int!
    }
    deleteFavorite: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    signup: { // args
      email: string; // String!
      firstName: string; // String!
      lastName: string; // String!
      password: string; // String!
      role?: string | null; // String
    }
    updateBook: { // args
      author: string; // String!
      bookFile: string; // String!
      categoryId: number; // Int!
      description: string; // String!
      id: number; // Int!
      image: string; // String!
      title: string; // String!
    }
    updateCategory: { // args
      id: number; // Int!
      name: string; // String!
    }
    updateUser: { // args
      firstName: string; // String!
      id: number; // Int!
      lastName: string; // String!
    }
  }
  Query: {
    oneBook: { // args
      id: number; // Int!
    }
    oneCategory: { // args
      id: number; // Int!
    }
    oneFavorite: { // args
      id: number; // Int!
    }
    oneUser: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}